version: '3.8'
services:
  db: 
    image: postgres:15
    container_name: db_app
    ports:
      - "1221:5432"  # Проброс порта, чтобы клиент мог подключиться
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Персистентное хранилище для данных
    restart: always  # Автоперезапуск контейнера в случае сбоя

  weather_r_w:
    build: 
      context: /WeatherRW/
    ports:
      - "9999:8000"
    depends_on:
      - db

  weather_data_service:
    build: 
      context: /WeatherDataService/
    ports:
      - "9998:8080"
    depends_on:
      - db
      - weather_r_w

volumes:
  postgres_data:  # Определение volume для хранения данных
